-- +migrate Up
CREATE TABLE IF NOT EXISTS problem (
  uuid UUID PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  author UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS algo (
  uuid UUID PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  author UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS data (
  uuid UUID PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  owner UUID NOT NULL
);

-- +migrate Down
DROP TABLE problem;
DROP TABLE algo;
DROP TABLE data;
